modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "modtemplate"
displayName = "Mod Template"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "cassiancc"
description = '''A mod template for Cassian's mods.'''

[[mixins]]
config = "modtemplate.mixins.json"

[[dependencies.modtemplate]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modtemplate]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"